name: Linter check
on:
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
